const Data=[ {
    "category":"cat",
    "id":20,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7147347PL.jpg",
    "price":25,
    "name":"Biscuit"
},
{
    "category":"cat",
    "id":21,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7147083PL.jpg",
    "price":62,
    "name":"Caesar"
},
{
    "category":"cat",
    "id":22,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7133544.jpg",
    "price":82,
    "name":"Dumpling"
},
{
    "category":"cat",
    "id":23,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/36929PL.jpg",
    "price":28,
    "name":"Hoagie"
},
{
    "category":"cat",
    "id":24,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/P1213L.jpg",
    "price":21,
    "name":"Lasagna"
},{
    "category":"cat",
    "id":25,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7147347PL.jpg",
    "price":27,
    "name":"Lentil"
},
{
    "category":"cat",
    "id":26,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7147083PL.jpg",
    "price":23,
    "name":"Pumpernickel"
},
{
    "category":"cat",
    "id":27,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7133544.jpg",
    "price":22,
    "name":"Schnitzel"
},
{
    "category":"cat",
    "id":28,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/36929PL.jpg",
    "price":28,
    "name":"Cannoli"
},
{
    "category":"cat",
    "id":29,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/P1213L.jpg",
    "price":32,
    "name":"Apricot"
},
{
    "category":"cat",
    "id":30,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7147083PL.jpg",
    "price":35,
    "name":"Cheddar"
},
{
    "category":"cat",
    "id":31,
    "path":"https://media.petsathome.com/wcsstore/pah-cas01//300/7133544.jpg",
    "price":60,
    "name":"Kumquat"
},]

export default Data